services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=brewerssupporter
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
